#ifndef DDSN_DEFINITIONS_H
#define DDSN_DEFINITIONS_H

#define DDSN_API_MESSAGE_TYPE_END		0
#define DDSN_API_MESSAGE_TYPE_STRING	1
#define DDSN_API_MESSAGE_TYPE_BYTES		2
#define DDSN_API_MESSAGE_TYPE_CLOSE		3
#define DDSN_API_MESSAGE_TYPE_ERROR		4

#define DDSN_PEER_MESSAGE_TYPE_END		0
#define DDSN_PEER_MESSAGE_TYPE_STRING	1
#define DDSN_PEER_MESSAGE_TYPE_BYTES	2
#define DDSN_PEER_MESSAGE_TYPE_CLOSE	3
#define DDSN_PEER_MESSAGE_TYPE_ERROR	4

#endif